In [1]:
import pandas as pd
import numpy as np
from IPython.display import Image
np.set_printoptions(precision = 3)
import matplotlib.pyplot as plt

#1. Loading the data set

In [4]:
df_ratings = pd.read_csv ('https://raw.githubusercontent.com/NatalieB-github/CE888/master/lab4-recommender/jester-data-1.csv', header=None)
df_ratings

0      1      2      3      4    ...    96     97     98     99     100
0       74  -7.82   8.79  -9.66  -8.16  ...  99.00  -5.63  99.00  99.00  99.00
1      100   4.08  -0.29   6.36   4.37  ...  -2.14   3.06   0.34  -4.32   1.07
2       49  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
3       48  99.00   8.35  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
4       91   8.50   4.61  -4.17  -5.39  ...   1.55   3.11   6.55   1.80   1.60
...    ...    ...    ...    ...    ...  ...    ...    ...    ...    ...    ...
24978  100   0.44   7.43   9.08   2.33  ...   9.03   6.55   8.69   8.79   7.43
24979   91   9.13  -8.16   8.59   9.08  ...  -8.20  -7.23  -8.59   9.13   8.45
24980   39  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24981   37  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24982   72   2.43   2.67  -3.98   4.27  ...  99.00  99.00  99.00  99.00  99.00

[24983 rows x 101 columns]

##1.1 Which value you should replace with NaNs?

In [45]:
df_ratings=df_ratings.replace(99.00, np.NaN)
df_ratings.head()

1     2     3     4     5     6    ...   95    96    97    98    99    100
0 -7.82  8.79 -9.66 -8.16 -7.52 -8.50  ...   NaN   NaN -5.63   NaN   NaN   NaN
1  4.08 -0.29  6.36  4.37 -2.38 -9.66  ... -0.19 -2.14  3.06  0.34 -4.32  1.07
2   NaN   NaN   NaN   NaN  9.03  9.27  ...   NaN   NaN   NaN   NaN   NaN   NaN
3   NaN  8.35   NaN   NaN  1.80  8.16  ...   NaN   NaN   NaN   NaN   NaN   NaN
4  8.50  4.61 -4.17 -5.39  1.36  1.60  ...  5.73  1.55  3.11  6.55  1.80  1.60

[5 rows x 100 columns]

##1.2 Removing a column

In [5]:
df_ratings.drop(columns=[0],axis=1,inplace=True)

##1.3 The best- and the worst-rated jokes

In [9]:
mean_ratings = df_ratings.mean(axis=0)
mean_ratings

1      0.904573
2      0.208460
3      0.316574
4     -1.449114
5      0.403556
         ...   
96     1.528003
97     1.673750
98     0.767692
99    -0.031244
100    1.354711
Length: 100, dtype: float64

In [17]:
pd.DataFrame(mean_ratings).nsmallest(10,0)


0
58 -3.833880
16 -3.104818
44 -2.111891
57 -1.990664
13 -1.762882
15 -1.706201
24 -1.687420
74 -1.553548
4  -1.449114
33 -1.368648

In [18]:
pd.DataFrame(mean_ratings).nlargest(10,0)


0
50  3.665085
89  3.574720
36  3.312500
27  3.189821
32  3.155988
35  3.006351
62  2.976021
29  2.972455
53  2.939463
49  2.771298

##1.4 Modify and use the helper function

In [20]:
arr = df_ratings.values
print(arr.shape)

(24983, 100)


In [21]:
rated = np.where(arr!=99)
print(len(rated[0]), rated[1].shape)

2498300 (2498300,)


In [23]:
def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(arr!=99)
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [28]:
new_arr, idx = replace(arr, 0.1)
new_arr

array([[-7.82,  8.79, -9.66, ...,   nan,   nan,   nan],
       [ 4.08, -0.29,  6.36, ...,  0.34, -4.32,  1.07],
       [  nan, 99.  ,   nan, ...,   nan,   nan,   nan],
       ...,
       [  nan,   nan,   nan, ...,   nan,   nan,   nan],
       [  nan,   nan,   nan, ...,   nan,   nan,   nan],
       [ 2.43,  2.67, -3.98, ..., 99.  ,   nan,   nan]])

In [25]:
arr[idx[0][0], idx[1][0]]

4.03

In [26]:
new_arr[idx[0][0], idx[1][0]]

99.0

##1.5 Use latent factor modeling

In [29]:
n_latent_factors = 2

latent_user_preferences = np.random.random((arr.shape[0], n_latent_factors))
latent_item_features = np.random.random((arr.shape[1], n_latent_factors))

In [30]:
latent_user_preferences

array([[0.409, 0.001],
       [0.695, 0.946],
       [0.611, 0.391],
       ...,
       [0.447, 0.624],
       [0.949, 0.342],
       [0.821, 0.402]])

In [31]:
latent_item_features

array([[0.167, 0.375],
       [0.026, 0.122],
       [0.242, 0.796],
       [0.273, 0.81 ],
       [0.916, 0.207],
       [0.242, 0.216],
       [0.77 , 0.123],
       [0.761, 0.484],
       [0.785, 0.263],
       [0.381, 0.276],
       [0.444, 0.437],
       [0.655, 0.428],
       [0.236, 0.303],
       [0.12 , 0.386],
       [0.822, 0.047],
       [0.996, 0.358],
       [0.295, 0.37 ],
       [0.849, 0.444],
       [0.475, 0.529],
       [0.55 , 0.906],
       [0.743, 0.007],
       [0.361, 0.37 ],
       [0.438, 0.587],
       [0.691, 0.079],
       [0.513, 0.601],
       [0.387, 0.604],
       [0.994, 0.419],
       [0.489, 0.13 ],
       [0.507, 0.009],
       [0.469, 0.491],
       [0.226, 0.591],
       [0.287, 0.66 ],
       [0.07 , 0.168],
       [0.502, 0.595],
       [0.449, 0.939],
       [0.377, 0.078],
       [0.61 , 0.616],
       [0.742, 0.78 ],
       [0.244, 0.973],
       [0.685, 0.148],
       [0.996, 0.09 ],
       [0.747, 0.916],
       [0.754, 0.668],
       [0.5

In [36]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
    #print(item_id)
    predicted_rating = predict_rating(user_id, item_id)
    err =  predicted_rating - rating
    #print(err)
    user_pref_values = latent_user_preferences[user_id]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    
def sgd(iterations):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    mse_history = []
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = arr[user_id, item_id]
                if not np.isnan(rating):
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 10000) == 0:
            print('Iteration %d/%d:\tMSE=%.6f' % (iteration, iterations, mse))
            mse_history.append(mse)
    return mse_history

In [ ]:
num_iter = 10
hist = sgd(num_iter)  # Note how the MSE decreases with the number of iterations
plt.figure()
plt.plot(np.arange(0, num_iter, 10), hist)
plt.xlabel("Iterations")
plt.ylabel("MSE")
plt.show()

In [38]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[0.558, 0.307, 0.286, ..., 0.552, 0.177, 0.852],
       [1.369, 0.704, 0.77 , ..., 1.585, 0.528, 2.204],
       [1.449, 0.765, 0.787, ..., 1.583, 0.52 , 2.286],
       ...,
       [0.924, 0.474, 0.521, ..., 1.074, 0.358, 1.49 ],
       [1.253, 0.678, 0.657, ..., 1.291, 0.418, 1.938],
       [1.432, 0.764, 0.766, ..., 1.527, 0.499, 2.241]])

In [40]:
values = [zip(arr[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = df_ratings.columns

In [41]:
comparison_data

1    ...                         100
0      (-7.82, 0.5578843830351572)  ...   (nan, 0.8523500170252103)
1       (4.08, 1.3693793826924137)  ...  (1.07, 2.2039026221862836)
2        (nan, 1.4494196724545425)  ...   (nan, 2.2864626713912775)
3        (nan, 0.6248067814684214)  ...   (nan, 0.9967068792991199)
4         (8.5, 1.730483969150703)  ...   (1.6, 2.7886187538430947)
...                            ...  ...                         ...
24978   (0.44, 1.7740955880777889)  ...   (7.43, 2.839348441427782)
24979     (9.13, 0.52037005744607)  ...  (8.45, 0.8237000800398049)
24980    (nan, 0.9244094617032569)  ...   (nan, 1.4896989376465135)
24981     (nan, 1.252763028206684)  ...   (nan, 1.9384658906405796)
24982   (2.43, 1.4318820859300923)  ...   (nan, 2.2410140948470256)

[24983 rows x 100 columns]

In [43]:
df = pd.read_excel('/content/movies_latent_factors.xlsx')
df

Movie ID  ...  Factor15
0         11  ... -0.248806
1         12  ...  1.274993
2         13  ... -0.419092
3         14  ... -0.681191
4         22  ... -2.292566
..       ...  ...       ...
95      9806  ...  1.017861
96     10020  ... -0.487076
97     36657  ...  0.067790
98     36658  ... -0.288130
99     36955  ... -0.022599

[100 rows x 17 columns]